let publicCard=null;
window.track=async function(type,targetId=null,metadata={}){if(!publicCard)return;try{await supabaseClient.from('card_events').insert({card_id:publicCard.id,event_type:type,target_id:targetId,visitor_id:getVisitor(),device_type:/Mobi/.test(navigator.userAgent)?'mobile':'desktop',browser:navigator.userAgent.slice(0,100),referrer:document.referrer||null,metadata})}catch{}}
(async()=>{const slug=new URLSearchParams(location.search).get('slug');if(!slug)return showUnavailable('Card not found','The card address is incomplete.');const {data:c,error}=await supabaseClient.from('digital_cards').select('*').eq('slug',slug).eq('status','published').single();if(error||!c)return showUnavailable('Card unavailable','This card may be private, unpublished, or no longer active.');publicCard=c;const {data:links}=await supabaseClient.from('social_links').select('*').eq('card_id',c.id).eq('is_enabled',true).order('sort_order');renderCard(c,links||[]);recordView(c.id)})();
function renderCard(c,links){document.title=c.seo_title||`${c.full_name} | Digital Business Card`;const card=document.getElementById('card');card.style.background=c.background_color||'#fff';card.style.color=c.text_color||'#111827';card.style.fontFamily=c.font_family||'DM Sans';const primary=c.primary_color||'#5b5cf0',secondary=c.secondary_color||'#9b5de5';document.getElementById('public-cover').style.background=c.gradient_background||`linear-gradient(135deg,${primary},${secondary})`;document.querySelector('meta[name="theme-color"]').content=primary;document.getElementById('name').textContent=c.full_name||'';document.getElementById('title').textContent=c.job_title||'';document.getElementById('company').textContent=c.company_name||'';document.getElementById('headline').textContent=c.headline||'';document.getElementById('bio').textContent=c.biography||'';const initials=(c.full_name||'DC').split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();const avatar=document.getElementById('avatar');avatar.style.borderRadius=c.profile_image_shape==='square'?'10px':c.profile_image_shape==='rounded'?'27px':'50%';avatar.innerHTML=c.profile_image_url?`<img src="${escapeHtml(c.profile_image_url)}" alt="${escapeHtml(c.full_name||'Profile photo')}">`:`<span>${initials}</span>`;renderActions(c,primary);renderSocials(links);document.getElementById('branding').hidden=c.show_branding===false;const qrUrl=`https://api.qrserver.com/v1/create-qr-code/?size=480x480&data=${encodeURIComponent(location.href)}`;document.getElementById('qr').src=qrUrl;document.getElementById('save').onclick=()=>saveVcard(c);document.getElementById('sticky-save').onclick=()=>saveVcard(c);document.getElementById('share-top').onclick=shareCard;document.getElementById('qr-top').onclick=()=>{document.getElementById('qr-dialog').showModal();track('qr_scan')};document.getElementById('close-qr').onclick=()=>document.getElementById('qr-dialog').close();document.getElementById('copy-link').onclick=copyLink;document.getElementById('loading').hidden=true;card.hidden=false;document.getElementById('sticky-save').hidden=false;if(window.lucide)lucide.createIcons()}
function renderActions(c,primary){const actions=[{label:'Call',icon:'phone',href:c.phone&&`tel:${c.phone}`,event:'phone_click'},{label:'Text',icon:'message-square-text',href:c.phone&&`sms:${c.phone}`,event:'text_click'},{label:'Email',icon:'mail',href:c.email&&`mailto:${c.email}`,event:'email_click'},{label:'Website',icon:'globe',href:normalizeUrl(c.website),event:'website_click'},{label:'Directions',icon:'map-pin',href:c.business_address&&`https://maps.google.com/?q=${encodeURIComponent(c.business_address)}`,event:'location_click'}].filter(x=>x.href).slice(0,4);const area=document.getElementById('actions');area.innerHTML=actions.map(a=>`<a class="action-tile" href="${escapeHtml(a.href)}" target="${a.href.startsWith('http')?'_blank':'_self'}" data-event="${a.event}" style="color:${primary};background:${primary}14"><i data-lucide="${a.icon}" size="19"></i><span>${a.label}</span></a>`).join('');area.querySelectorAll('[data-event]').forEach(link=>link.addEventListener('click',()=>track(link.dataset.event)))}
function renderSocials(links){if(!links.length)return;document.getElementById('social-section').hidden=false;document.getElementById('socials').innerHTML=links.map(link=>`<a class="social-chip" href="${escapeHtml(normalizeUrl(link.url))}" target="_blank" data-id="${link.id}"><i data-lucide="${platformIcon(link.platform)}" size="16"></i>${escapeHtml(link.label||link.platform)}</a>`).join('');document.querySelectorAll('.social-chip').forEach(link=>link.addEventListener('click',()=>track('social_click',link.dataset.id)))}
function platformIcon(platform){const key=String(platform).toLowerCase();return({instagram:'instagram',facebook:'facebook',linkedin:'linkedin',youtube:'youtube',whatsapp:'message-circle',website:'globe',tiktok:'music-2',x:'at-sign',pinterest:'pin'})[key]||'link'}
async function shareCard(){const data={title:publicCard?.full_name||'Digital business card',text:`Connect with ${publicCard?.full_name||'me'}`,url:location.href};try{if(navigator.share)await navigator.share(data);else await navigator.clipboard.writeText(location.href);track('share_click');toast(navigator.share?'Share sheet opened':'Card link copied')}catch{}}
async function copyLink(){await navigator.clipboard.writeText(location.href);track('share_click');toast('Card link copied')}
async function recordView(cardId){try{await supabaseClient.from('card_views').insert({card_id:cardId,visitor_id:getVisitor(),device_type:/Mobi/.test(navigator.userAgent)?'mobile':'desktop',browser:navigator.userAgent.slice(0,100),referrer:document.referrer||null})}catch{}}
function getVisitor(){let id=localStorage.dotcoVisitor;if(!id){id=crypto.randomUUID();localStorage.dotcoVisitor=id}return id}
function normalizeUrl(url){if(!url)return'';return /^https?:\/\//i.test(url)?url:`https://${url}`}
function vcardEscape(value=''){return String(value).replace(/([,;\\])/g,'\\$1').replace(/\n/g,'\\n')}
function saveVcard(c){const names=(c.full_name||'').trim().split(/\s+/);const last=names.length>1?names.pop():'';const first=names.join(' ');const v=`BEGIN:VCARD\r\nVERSION:3.0\r\nN:${vcardEscape(last)};${vcardEscape(first)};;;\r\nFN:${vcardEscape(c.full_name||'')}\r\nORG:${vcardEscape(c.company_name||'')}\r\nTITLE:${vcardEscape(c.job_title||'')}\r\nTEL;TYPE=CELL:${vcardEscape(c.phone||'')}\r\nEMAIL;TYPE=INTERNET:${vcardEscape(c.email||'')}\r\nURL:${vcardEscape(c.website||'')}\r\nADR;TYPE=WORK:;;${vcardEscape(c.business_address||'')};;;;\r\nNOTE:${vcardEscape(c.biography||'')}\r\nEND:VCARD\r\n`;const url=URL.createObjectURL(new Blob([v],{type:'text/vcard;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${c.slug||'contact'}.vcf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);track('contact_save');toast('Contact downloaded')}
function showUnavailable(title,message){document.getElementById('loading').innerHTML=`<span class="empty-icon"><i data-lucide="link-2-off" size="28"></i></span><h2>${escapeHtml(title)}</h2><p class="muted">${escapeHtml(message)}</p>`;if(window.lucide)lucide.createIcons()}
